import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { ReminderActivityAction, ReminderPriority, ReminderStatus, ReminderType } from '@repo/database';
import { EventNames } from '../../common/events/event-names.constant';
import type { RequestUser } from '../../auth/types/request-user.interface';
import { ReminderCreatedEvent, ReminderStatusChangedEvent } from './events/reminder.events';
import { RemindersRepository } from './reminders.repository';
import type { CreateReminderDto } from './dto/create-reminder.dto';
import type { UpdateReminderDto } from './dto/update-reminder.dto';
import type { ListRemindersDto } from './dto/list-reminders.dto';
import type { SnoozeReminderDto } from './dto/snooze-reminder.dto';
import type { CompleteReminderDto, DismissReminderDto } from './dto/complete-reminder.dto';
// ── Valid status transitions ───────────────────────────────────────────────────

const STATUS_TRANSITIONS: Partial<Record<ReminderStatus, ReminderStatus[]>> = {
  PENDING:      ['ACKNOWLEDGED', 'SNOOZED', 'COMPLETED', 'DISMISSED'],
  ACKNOWLEDGED: ['SNOOZED', 'COMPLETED', 'DISMISSED', 'PENDING'],
  SNOOZED:      ['PENDING', 'COMPLETED', 'DISMISSED'],
  EXPIRED:      ['PENDING', 'COMPLETED', 'DISMISSED'],
};

@Injectable()
export class RemindersService {
  constructor(
    private readonly repo: RemindersRepository,
    private readonly events: EventEmitter2,
  ) {}

  // ── List + Action Center ──────────────────────────────────────────────────

  async list(user: RequestUser, dto: ListRemindersDto) {
    const { data, total } = await this.repo.findMany(user.organizationId, dto);
    return { data, total };
  }

  async actionCenter(user: RequestUser) {
    return this.repo.actionCenter(user.organizationId, user.userId);
  }

  async stats(user: RequestUser) {
    return this.repo.stats(user.organizationId, user.userId);
  }

  // ── CRUD ──────────────────────────────────────────────────────────────────

  async create(user: RequestUser, dto: CreateReminderDto) {
    const priority = dto.priority ?? this.inferPriority(dto.dueAt);
    const reminder = await this.repo.create({
      organizationId:  user.organizationId,
      type:            dto.type,
      priority,
      title:           dto.title,
      ...(dto.description   && { description: dto.description }),
      ...(dto.dueAt         && { dueAt: new Date(dto.dueAt) }),
      ...(dto.submissionId  && { submissionId: dto.submissionId }),
      ...(dto.interviewId   && { interviewId: dto.interviewId }),
      ...(dto.candidateId   && { candidateId: dto.candidateId }),
      ...(dto.jobId         && { jobId: dto.jobId }),
      assigneeId:  dto.assigneeId ?? user.userId,
      createdById: user.userId,
      isAutoGenerated: false,
    });

    await this.repo.addActivity({
      reminderId:     reminder.id,
      organizationId: user.organizationId,
      actorId:        user.userId,
      action:         ReminderActivityAction.CREATED,
    });

    this.events.emit(
      EventNames.REMINDER_CREATED,
      new ReminderCreatedEvent(
        { actorId: user.userId, actorEmail: user.email, organizationId: user.organizationId },
        { reminderId: reminder.id, type: reminder.type, priority: reminder.priority, assigneeId: reminder.assigneeId, isAutoGenerated: false },
      ),
    );

    return reminder;
  }

  async findById(user: RequestUser, id: string) {
    const reminder = await this.repo.findById(id, user.organizationId);
    if (!reminder) throw new NotFoundException('Reminder not found');

    // Record view without flooding the activity log (only first view per session is meaningful)
    return reminder;
  }

  async update(user: RequestUser, id: string, dto: UpdateReminderDto) {
    const reminder = await this.repo.findById(id, user.organizationId);
    if (!reminder) throw new NotFoundException('Reminder not found');

    const updated = await this.repo.update(id, {
      ...(dto.priority    !== undefined && { priority: dto.priority }),
      ...(dto.title       !== undefined && { title: dto.title }),
      ...(dto.description !== undefined && { description: dto.description }),
      ...(dto.dueAt       !== undefined && { dueAt: dto.dueAt ? new Date(dto.dueAt) : null }),
    });

    await this.repo.addActivity({
      reminderId: id, organizationId: user.organizationId,
      actorId: user.userId, action: ReminderActivityAction.UPDATED,
    });

    return updated;
  }

  async delete(user: RequestUser, id: string) {
    const reminder = await this.repo.findById(id, user.organizationId);
    if (!reminder) throw new NotFoundException('Reminder not found');
    await this.repo.softDelete(id);
  }

  // ── State transitions ─────────────────────────────────────────────────────

  async acknowledge(user: RequestUser, id: string) {
    return this.transition(user, id, 'ACKNOWLEDGED', ReminderActivityAction.ACKNOWLEDGED, {
      acknowledgedAt: new Date(),
    });
  }

  async complete(user: RequestUser, id: string, dto: CompleteReminderDto) {
    return this.transition(user, id, 'COMPLETED', ReminderActivityAction.COMPLETED, {
      completedAt: new Date(),
    }, dto.note);
  }

  async snooze(user: RequestUser, id: string, dto: SnoozeReminderDto) {
    const snoozedUntil = new Date(Date.now() + dto.minutes * 60_000);
    return this.transition(user, id, 'SNOOZED', ReminderActivityAction.SNOOZED, {
      snoozedUntil,
    }, dto.note, { snoozedUntilIso: snoozedUntil.toISOString(), minutes: dto.minutes });
  }

  async dismiss(user: RequestUser, id: string, dto: DismissReminderDto) {
    return this.transition(user, id, 'DISMISSED', ReminderActivityAction.DISMISSED, {
      dismissedAt: new Date(),
    }, dto.reason);
  }

  async reopen(user: RequestUser, id: string) {
    const reminder = await this.repo.findById(id, user.organizationId);
    if (!reminder) throw new NotFoundException('Reminder not found');
    if (reminder.status === 'PENDING') return reminder;

    const updated = await this.repo.update(id, {
      status:        'PENDING',
      completedAt:   null,
      dismissedAt:   null,
      snoozedUntil:  null,
      acknowledgedAt: null,
    });

    await this.repo.addActivity({
      reminderId: id, organizationId: user.organizationId,
      actorId: user.userId, action: ReminderActivityAction.REOPENED,
    });

    return updated;
  }

  // ── Auto-creation (called by ReminderGeneratorService) ────────────────────

  async createSystem(params: {
    organizationId: string;
    type:           ReminderType;
    priority:       ReminderPriority;
    title:          string;
    description?:   string;
    dueAt?:         Date;
    assigneeId:     string;
    createdById:    string;
    submissionId?:  string;
    interviewId?:   string;
    candidateId?:   string;
    jobId?:         string;
    metadata?:      Record<string, unknown>;
  }) {
    const reminder = await this.repo.create({
      organizationId:  params.organizationId,
      type:            params.type,
      priority:        params.priority,
      title:           params.title,
      ...(params.description  && { description: params.description }),
      ...(params.dueAt        && { dueAt: params.dueAt }),
      ...(params.submissionId && { submissionId: params.submissionId }),
      ...(params.interviewId  && { interviewId: params.interviewId }),
      ...(params.candidateId  && { candidateId: params.candidateId }),
      ...(params.jobId        && { jobId: params.jobId }),
      ...(params.metadata     && { metadata: params.metadata as never }),
      assigneeId:     params.assigneeId,
      createdById:    params.createdById,
      isAutoGenerated: true,
    });

    await this.repo.addActivity({
      reminderId:     reminder.id,
      organizationId: params.organizationId,
      actorId:        params.createdById,
      action:         ReminderActivityAction.CREATED,
      note:           'Auto-generated by system',
    });

    this.events.emit(
      EventNames.REMINDER_CREATED,
      new ReminderCreatedEvent(
        { actorId: params.createdById, actorEmail: '', organizationId: params.organizationId },
        { reminderId: reminder.id, type: reminder.type, priority: reminder.priority, assigneeId: reminder.assigneeId, isAutoGenerated: true },
      ),
    );

    return reminder;
  }

  // ── Private helpers ───────────────────────────────────────────────────────

  private async transition(
    user:     RequestUser,
    id:       string,
    toStatus: ReminderStatus,
    action:   ReminderActivityAction,
    extraData: Record<string, unknown>,
    note?:    string,
    metadata?: Record<string, unknown>,
  ) {
    const reminder = await this.repo.findById(id, user.organizationId);
    if (!reminder) throw new NotFoundException('Reminder not found');

    const allowed = STATUS_TRANSITIONS[reminder.status] ?? [];
    if (!allowed.includes(toStatus)) {
      throw new BadRequestException(
        `Cannot transition from ${reminder.status} to ${toStatus}`,
      );
    }

    const updated = await this.repo.update(id, { status: toStatus, ...extraData });

    await this.repo.addActivity({
      reminderId:     id,
      organizationId: user.organizationId,
      actorId:        user.userId,
      action,
      ...(note     && { note }),
      ...(metadata && { metadata: metadata as never }),
    });

    this.events.emit(
      EventNames.REMINDER_UPDATED,
      new ReminderStatusChangedEvent(
        { actorId: user.userId, actorEmail: user.email, organizationId: user.organizationId },
        { reminderId: id, fromStatus: reminder.status, toStatus, assigneeId: reminder.assigneeId },
      ),
    );

    return updated;
  }

  /** Infer a default priority based on how soon the due date is. */
  private inferPriority(dueAt?: string): ReminderPriority {
    if (!dueAt) return 'MEDIUM';
    const msUntilDue = new Date(dueAt).getTime() - Date.now();
    const hoursUntilDue = msUntilDue / 3_600_000;
    if (hoursUntilDue < 0)  return 'CRITICAL'; // already overdue
    if (hoursUntilDue < 24) return 'HIGH';
    if (hoursUntilDue < 72) return 'MEDIUM';
    return 'LOW';
  }
}
