export type ReminderType =
  | 'UPCOMING_INTERVIEW'
  | 'INTERVIEW_FEEDBACK_PENDING'
  | 'OVERDUE_SUBMISSION_FOLLOWUP'
  | 'CANDIDATE_AVAILABILITY_FOLLOWUP'
  | 'RECRUITER_ACTION_REQUIRED'
  | 'STALLED_WORKFLOW'
  | 'OVERDUE_INTERVIEW_SCHEDULING'
  | 'PENDING_RECRUITER_REVIEW'
  | 'INTERVIEW_CONFIRMATION_NEEDED'
  | 'CUSTOM';

export type ReminderStatus =
  | 'PENDING'
  | 'ACKNOWLEDGED'
  | 'SNOOZED'
  | 'COMPLETED'
  | 'DISMISSED'
  | 'EXPIRED';

export type ReminderPriority = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';

export type ReminderActivityAction =
  | 'CREATED'
  | 'VIEWED'
  | 'ACKNOWLEDGED'
  | 'SNOOZED'
  | 'COMPLETED'
  | 'DISMISSED'
  | 'ESCALATED'
  | 'REOPENED'
  | 'UPDATED';

// ── Display helpers ────────────────────────────────────────────────────────────

export const REMINDER_TYPE_LABELS: Record<ReminderType, string> = {
  UPCOMING_INTERVIEW:             'Upcoming Interview',
  INTERVIEW_FEEDBACK_PENDING:     'Feedback Pending',
  OVERDUE_SUBMISSION_FOLLOWUP:    'Submission Follow-up',
  CANDIDATE_AVAILABILITY_FOLLOWUP:'Availability Follow-up',
  RECRUITER_ACTION_REQUIRED:      'Action Required',
  STALLED_WORKFLOW:               'Stalled Workflow',
  OVERDUE_INTERVIEW_SCHEDULING:   'Schedule Interview',
  PENDING_RECRUITER_REVIEW:       'Pending Review',
  INTERVIEW_CONFIRMATION_NEEDED:  'Needs Confirmation',
  CUSTOM:                         'Custom',
};

export const REMINDER_STATUS_LABELS: Record<ReminderStatus, string> = {
  PENDING:      'Pending',
  ACKNOWLEDGED: 'Acknowledged',
  SNOOZED:      'Snoozed',
  COMPLETED:    'Completed',
  DISMISSED:    'Dismissed',
  EXPIRED:      'Expired',
};

export const REMINDER_PRIORITY_LABELS: Record<ReminderPriority, string> = {
  CRITICAL: 'Critical',
  HIGH:     'High',
  MEDIUM:   'Medium',
  LOW:      'Low',
};

// ── Mini view shapes ───────────────────────────────────────────────────────────

interface UserMini {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
}

interface CandidateMini {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
}

interface InterviewMini {
  id: string;
  round: number;
  roundLabel: string | null;
  type: string;
  status: string;
  scheduledAt: string | null;
}

interface SubmissionMini {
  id: string;
  status: string;
}

interface JobMini {
  id: string;
  reqId: string;
  title: string;
  department: string | null;
}

// ── Domain types ───────────────────────────────────────────────────────────────

export interface ReminderActivityView {
  id: string;
  reminderId: string;
  actorId: string;
  action: ReminderActivityAction;
  note: string | null;
  metadata: Record<string, unknown>;
  createdAt: string;
  actor: { id: string; firstName: string; lastName: string };
}

export interface ReminderListItem {
  id: string;
  organizationId: string;
  type: ReminderType;
  priority: ReminderPriority;
  status: ReminderStatus;
  title: string;
  description: string | null;
  dueAt: string | null;
  snoozedUntil: string | null;
  acknowledgedAt: string | null;
  completedAt: string | null;
  dismissedAt: string | null;
  isAutoGenerated: boolean;
  submissionId: string | null;
  interviewId: string | null;
  candidateId: string | null;
  jobId: string | null;
  assigneeId: string;
  createdById: string;
  metadata: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  assignee: UserMini;
  candidate: CandidateMini | null;
  interview: InterviewMini | null;
  submission: SubmissionMini | null;
  job: JobMini | null;
}

export interface ReminderDetail extends ReminderListItem {
  createdBy: UserMini;
  activities: ReminderActivityView[];
}

// ── Stats & Action Center ──────────────────────────────────────────────────────

export interface ReminderStats {
  total: number;
  pending: number;
  overdue: number;
  critical: number;
  completedToday: number;
}

export interface ActionCenterStats {
  total: number;
  overdue: number;
  dueToday: number;
  upcoming: number;
  pendingFeedback: number;
  critical: number;
}

export interface ActionCenter {
  stats: ActionCenterStats;
  sections: {
    overdue:        ReminderListItem[];
    dueToday:       ReminderListItem[];
    upcoming:       ReminderListItem[];
    pendingFeedback: ReminderListItem[];
  };
}

// ── Query params ───────────────────────────────────────────────────────────────

export interface ListRemindersParams {
  page?:       number;
  limit?:      number;
  status?:     ReminderStatus[];
  type?:       ReminderType[];
  priority?:   ReminderPriority[];
  assigneeId?: string;
  submissionId?: string;
  interviewId?: string;
  candidateId?: string;
  sortBy?:     'dueAt' | 'priority' | 'createdAt' | 'status';
  sortOrder?:  'asc' | 'desc';
}

// ── DTOs ───────────────────────────────────────────────────────────────────────

export interface CreateReminderDto {
  type:          ReminderType;
  priority?:     ReminderPriority;
  title:         string;
  description?:  string;
  dueAt?:        string;
  submissionId?: string;
  interviewId?:  string;
  candidateId?:  string;
  jobId?:        string;
  assigneeId?:   string;
}

export interface UpdateReminderDto {
  priority?:    ReminderPriority;
  title?:       string;
  description?: string;
  dueAt?:       string | null;
}

export interface SnoozeReminderDto {
  minutes: number;
  note?:   string;
}

export interface CompleteReminderDto {
  note?: string;
}

export interface DismissReminderDto {
  reason?: string;
}
