import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { OnEvent } from '@nestjs/event-emitter';

import type { EnvConfig } from '../../config';
import type { RequestUser } from '../../auth/types/request-user.interface';
import { EventNames } from '../../common/events/event-names.constant';
import { PrismaService } from '../../database/prisma.service';
import { EmailService } from '../../email/email.service';
import { NotificationsRepository } from './notifications.repository';

const REMINDER_EMAIL_PRIORITIES = new Set(['HIGH', 'CRITICAL']);
const REMINDER_EMAIL_DUE_SOON_HOURS = 48;
const INTERVIEW_UPCOMING_EMAIL_WINDOW_HOURS = 24;

@Injectable()
export class NotificationsService {
  private readonly logger = new Logger(NotificationsService.name);

  constructor(
    private readonly repo: NotificationsRepository,
    private readonly db: PrismaService,
    private readonly email: EmailService,
    private readonly config: ConfigService<EnvConfig, true>,
  ) {}

  // ── User-facing notification API ──────────────────────────────────────────

  async list(user: RequestUser, page: number, limit: number, unreadOnly = false) {
    const { data, total } = await this.repo.findForRecipient(
      user.organizationId, user.userId, page, limit, unreadOnly,
    );
    return { data, total };
  }

  async unreadCount(user: RequestUser) {
    const count = await this.repo.unreadCount(user.organizationId, user.userId);
    return { count };
  }

  async markRead(user: RequestUser, id: string) {
    const result = await this.repo.markRead(id, user.userId);
    if (result.count === 0) throw new NotFoundException('Notification not found');
  }

  async markAllRead(user: RequestUser) {
    await this.repo.markAllRead(user.organizationId, user.userId);
  }

  // ── Multi-channel dispatch (in-app + email) ────────────────────────────────
  //
  // Dispatch handlers below listen for domain events and decide:
  //   1. who to notify
  //   2. which channels to use (always IN_APP; EMAIL when conditions are met)
  //   3. what template + payload to send
  //
  // All handlers swallow their own errors so a delivery failure never breaks
  // the originating operation (the recruiter shouldn't get a 500 because an
  // email queue rejected a job).

  /**
   * Reminder created -> in-app notification for the assignee.
   * Plus email if (a) org email is enabled and (b) priority is HIGH/CRITICAL
   * or the reminder is due within 48h.
   */
  @OnEvent(EventNames.REMINDER_CREATED)
  async onReminderCreated(event: {
    reminderId:      string;
    organizationId:  string;
    actorId:         string;
    assigneeId:      string;
    isAutoGenerated: boolean;
  }) {
    // Manually-created reminders are created BY the recruiter — no need to
    // ping them in-app or email. Auto-generated reminders surface as
    // notifications because the system created them on the user's behalf.
    if (!event.isAutoGenerated) return;

    try {
      const reminder = await this.db.reminder.findUnique({
        where: { id: event.reminderId },
        include: {
          assignee: { select: { id: true, email: true, firstName: true, lastName: true } },
        },
      });
      if (!reminder) return;

      const actionUrl = this.resolveReminderContextUrl(reminder);

      // 1. In-app notification (always).
      await this.repo.createForReminder({
        organizationId: reminder.organizationId,
        recipientId:    reminder.assigneeId,
        reminderId:     reminder.id,
        title:          reminder.title,
        ...(reminder.description ? { body: reminder.description } : {}),
        ...(actionUrl ? { actionUrl } : {}),
      });

      // 2. Email — gated by org settings + priority + due window.
      const shouldEmail = await this.shouldEmailReminder(reminder);
      if (shouldEmail && reminder.assignee) {
        const fullUrl = actionUrl
          ? `${this.config.get('APP_URL', { infer: true })}${actionUrl}`
          : this.config.get('APP_URL', { infer: true });
        await this.email.send({
          template:       'reminder_due_soon',
          to:             reminder.assignee.email,
          organizationId: reminder.organizationId,
          recipientUserId: reminder.assignee.id,
          resourceType:   'Reminder',
          resourceId:     reminder.id,
          payload: {
            recipientName:       `${reminder.assignee.firstName} ${reminder.assignee.lastName}`.trim(),
            reminderTitle:       reminder.title,
            reminderDescription: reminder.description ?? '',
            dueAt:               reminder.dueAt ? reminder.dueAt.toLocaleString() : 'No deadline',
            contextUrl:          fullUrl,
          },
        });
      }
    } catch (err) {
      this.logger.error({ err, reminderId: event.reminderId }, 'Reminder notification dispatch failed');
    }
  }

  /**
   * Interview moved to COMPLETED or FEEDBACK_PENDING -> email the interviewer
   * if no feedback has been submitted yet.
   */
  @OnEvent(EventNames.INTERVIEW_STATUS_CHANGED)
  async onInterviewStatusChanged(event: {
    interviewId:   string;
    organizationId: string;
    fromStatus:    string;
    toStatus:      string;
  }) {
    if (event.toStatus !== 'COMPLETED' && event.toStatus !== 'FEEDBACK_PENDING') return;

    try {
      const interview = await this.db.interview.findUnique({
        where: { id: event.interviewId },
        include: {
          candidate: { select: { firstName: true, lastName: true } },
          job:       { select: { id: true, title: true } },
          feedback:  { select: { id: true } },
        },
      });
      if (!interview) return;

      // Skip if feedback already exists from someone — the dispatcher only
      // chases the first submitter to avoid noisy nags.
      if (interview.feedback.length > 0) return;

      const interviewerUser = interview.interviewerId
        ? await this.db.user.findUnique({
            where: { id: interview.interviewerId },
            select: { id: true, email: true, firstName: true, lastName: true },
          })
        : null;
      if (!interviewerUser) return;

      const appUrl = this.config.get('APP_URL', { infer: true });
      const actionPath = `/interviews/${interview.id}`;

      await this.repo.create({
        organizationId: interview.organizationId,
        recipientId:    interviewerUser.id,
        title:          `Feedback pending: ${interview.candidate.firstName} ${interview.candidate.lastName}`,
        body:           `Submit your feedback for the ${interview.job.title} interview.`,
        actionUrl:      actionPath,
        channel:        'IN_APP',
        status:         'DELIVERED',
        deliveredAt:    new Date(),
        metadata:       { interviewId: interview.id, jobId: interview.job.id } as never,
      });

      if (!(await this.isOrgEmailEnabled(interview.organizationId))) return;

      await this.email.send({
        template:       'interview_feedback_pending',
        to:             interviewerUser.email,
        organizationId: interview.organizationId,
        recipientUserId: interviewerUser.id,
        resourceType:   'Interview',
        resourceId:     interview.id,
        payload: {
          recipientName: `${interviewerUser.firstName} ${interviewerUser.lastName}`.trim(),
          candidateName: `${interview.candidate.firstName} ${interview.candidate.lastName}`.trim(),
          jobTitle:      interview.job.title,
          completedAt:   (interview.completedAt ?? new Date()).toLocaleString(),
          feedbackUrl:   `${appUrl}${actionPath}`,
        },
      });
    } catch (err) {
      this.logger.error({ err, interviewId: event.interviewId }, 'Interview feedback notification dispatch failed');
    }
  }

  /**
   * Interview scheduled -> in-app for the interviewer. Email if scheduled
   * within the next 24h (used by recruiters scheduling same-day rounds).
   */
  @OnEvent(EventNames.INTERVIEW_SCHEDULED)
  async onInterviewScheduled(event: {
    interviewId:    string;
    organizationId: string;
  }) {
    try {
      const interview = await this.db.interview.findUnique({
        where: { id: event.interviewId },
        include: {
          candidate: { select: { firstName: true, lastName: true } },
          job:       { select: { id: true, title: true } },
        },
      });
      if (!interview || !interview.interviewerId || !interview.scheduledAt) return;

      const interviewerUser = await this.db.user.findUnique({
        where: { id: interview.interviewerId },
        select: { id: true, email: true, firstName: true, lastName: true },
      });
      if (!interviewerUser) return;

      const appUrl = this.config.get('APP_URL', { infer: true });
      const actionPath = `/interviews/${interview.id}`;

      await this.repo.create({
        organizationId: interview.organizationId,
        recipientId:    interviewerUser.id,
        title:          `Interview scheduled: ${interview.candidate.firstName} ${interview.candidate.lastName}`,
        body:           `${interview.scheduledAt.toLocaleString()} - ${interview.job.title}`,
        actionUrl:      actionPath,
        channel:        'IN_APP',
        status:         'DELIVERED',
        deliveredAt:    new Date(),
        metadata:       { interviewId: interview.id, jobId: interview.job.id } as never,
      });

      const hoursUntil = (interview.scheduledAt.getTime() - Date.now()) / (1000 * 60 * 60);
      if (hoursUntil > INTERVIEW_UPCOMING_EMAIL_WINDOW_HOURS) return;
      if (!(await this.isOrgEmailEnabled(interview.organizationId))) return;

      await this.email.send({
        template:       'interview_upcoming',
        to:             interviewerUser.email,
        organizationId: interview.organizationId,
        recipientUserId: interviewerUser.id,
        resourceType:   'Interview',
        resourceId:     interview.id,
        payload: {
          recipientName:    `${interviewerUser.firstName} ${interviewerUser.lastName}`.trim(),
          candidateName:    `${interview.candidate.firstName} ${interview.candidate.lastName}`.trim(),
          jobTitle:         interview.job.title,
          scheduledAtHuman: interview.scheduledAt.toLocaleString(),
          interviewUrl:     `${appUrl}${actionPath}`,
        },
      });
    } catch (err) {
      this.logger.error({ err, interviewId: event.interviewId }, 'Interview scheduled notification dispatch failed');
    }
  }

  // ── Internal helpers ──────────────────────────────────────────────────────

  private resolveReminderContextUrl(reminder: {
    submissionId: string | null;
    interviewId:  string | null;
    candidateId:  string | null;
    jobId:        string | null;
  }): string | undefined {
    if (reminder.submissionId) return `/submissions/${reminder.submissionId}`;
    if (reminder.interviewId)  return `/interviews/${reminder.interviewId}`;
    if (reminder.candidateId)  return `/candidates/${reminder.candidateId}`;
    if (reminder.jobId)        return `/jobs/${reminder.jobId}`;
    return undefined;
  }

  private async shouldEmailReminder(reminder: {
    organizationId: string;
    priority:       string;
    dueAt:          Date | null;
  }): Promise<boolean> {
    if (!(await this.isOrgEmailEnabled(reminder.organizationId))) return false;
    if (REMINDER_EMAIL_PRIORITIES.has(reminder.priority)) return true;
    if (reminder.dueAt) {
      const hoursUntilDue = (reminder.dueAt.getTime() - Date.now()) / (1000 * 60 * 60);
      if (hoursUntilDue <= REMINDER_EMAIL_DUE_SOON_HOURS) return true;
    }
    return false;
  }

  private async isOrgEmailEnabled(organizationId: string): Promise<boolean> {
    const settings = await this.db.organizationSettings.findUnique({
      where: { organizationId },
      select: { emailNotificationsEnabled: true },
    });
    // Default to enabled if settings row doesn't exist yet — matches the
    // schema default of `true` so a fresh org doesn't silently drop emails.
    return settings?.emailNotificationsEnabled ?? true;
  }
}
