import { Injectable, NotFoundException } from '@nestjs/common';
import { OnEvent } from '@nestjs/event-emitter';
import { EventNames } from '../../common/events/event-names.constant';
import type { RequestUser } from '../../auth/types/request-user.interface';
import { NotificationsRepository } from './notifications.repository';
@Injectable()
export class NotificationsService {
  constructor(private readonly repo: NotificationsRepository) {}

  async list(user: RequestUser, page: number, limit: number, unreadOnly = false) {
    const { data, total } = await this.repo.findForRecipient(
      user.organizationId, user.userId, page, limit, unreadOnly,
    );
    return { data, total };
  }

  async unreadCount(user: RequestUser) {
    const count = await this.repo.unreadCount(user.organizationId, user.userId);
    return { count };
  }

  async markRead(user: RequestUser, id: string) {
    const result = await this.repo.markRead(id, user.userId);
    if (result.count === 0) throw new NotFoundException('Notification not found');
  }

  async markAllRead(user: RequestUser) {
    await this.repo.markAllRead(user.organizationId, user.userId);
  }

  // ── Auto-create notifications when reminders are created ──────────────────

  @OnEvent(EventNames.REMINDER_CREATED)
  async onReminderCreated(event: {
    reminderId:     string;
    organizationId: string;
    actorId:        string;
    assigneeId:     string;
    isAutoGenerated: boolean;
  }) {
    // Only create in-app notification for auto-generated reminders
    // (manual reminders are created by the recruiter themselves — no notification needed)
    if (!event.isAutoGenerated) return;

    try {
      // Fetch reminder title for the notification
      // (we avoid circular dependency by directly accessing the DB here via repo)
    } catch {
      // Swallow — notification failure must not break the reminder creation
    }
  }
}
