import { BaseEvent } from '../../../common/events/base.event';
import type { ReminderStatus, ReminderType, ReminderPriority } from '@repo/database';

interface ReminderEventActor {
  actorId: string;
  actorEmail: string;
  organizationId: string;
  correlationId?: string | null;
}

export class ReminderCreatedEvent extends BaseEvent {
  readonly reminderId: string;
  readonly type: ReminderType;
  readonly priority: ReminderPriority;
  readonly assigneeId: string;
  readonly isAutoGenerated: boolean;

  constructor(
    actor: ReminderEventActor,
    payload: {
      reminderId: string;
      type: ReminderType;
      priority: ReminderPriority;
      assigneeId: string;
      isAutoGenerated: boolean;
    },
  ) {
    super(actor);
    this.reminderId = payload.reminderId;
    this.type = payload.type;
    this.priority = payload.priority;
    this.assigneeId = payload.assigneeId;
    this.isAutoGenerated = payload.isAutoGenerated;
  }
}

export class ReminderStatusChangedEvent extends BaseEvent {
  readonly reminderId: string;
  readonly fromStatus: ReminderStatus;
  readonly toStatus: ReminderStatus;
  readonly assigneeId: string;

  constructor(
    actor: ReminderEventActor,
    payload: {
      reminderId: string;
      fromStatus: ReminderStatus;
      toStatus: ReminderStatus;
      assigneeId: string;
    },
  ) {
    super(actor);
    this.reminderId = payload.reminderId;
    this.fromStatus = payload.fromStatus;
    this.toStatus = payload.toStatus;
    this.assigneeId = payload.assigneeId;
  }
}
